apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openmcpmigrations.nanum.co.kr
spec:
  group: nanum.co.kr
  names:
    kind: OpenMCPMigration
    listKind: OpenMCPMigrationList
    plural: openmcpmigrations
    singular: openmcpmigration
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OpenMCPMigration is the Schema for the openmcpmigrations API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OpenMCPMigrationSpec defines the desired state of OpenMCPMigration
          properties:
            MigrationServiceSource:
              description: container service list spec
              items:
                properties:
                  MigrationSource:
                    description: container service spec
                    items:
                      properties:
                        NameSpace:
                          type: string
                        ResourceName:
                          type: string
                        ResourceType:
                          type: string
                        SourceCluster:
                          type: string
                        TargetCluster:
                          description: Migration source
                          type: string
                      required:
                      - NameSpace
                      - ResourceName
                      - ResourceType
                      - SourceCluster
                      - TargetCluster
                      type: object
                    type: array
                  VolumePath:
                    type: string
                required:
                - MigrationSource
                - VolumePath
                type: object
              type: array
          required:
          - MigrationServiceSource
          type: object
        status:
          description: OpenMCPMigrationStatus defines the observed state of OpenMCPMigration
          properties:
            MigrationSpec:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
            Reason:
              type: string
          required:
          - MigrationSpec
          - Reason
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
