apiVersion: nanum.co.kr/v1alpha1
kind: OpenMCPMigration
metadata:
  name: example-openmcpmigration
spec:
  MigrationServiceSource:
  - MigrationSource:
    - ResourceName: testim-dp
      ResourceType: dp
      NameSpace: demo-service
      SourceClusterName: cluster1
      TargetClusterName: cluster2
    - ResourceName: testim-sv
      ResourceType: svc
      NameSpace: demo-service
      SourceClusterName: cluster1
      TargetClusterName: cluster2
    - ResourceName: testim-pv
      ResourceType: pv
      NameSpace: demo-service
      SourceClusterName: cluster1
      TargetClusterName: cluster2
    - ResourceName: testim-pvc
      ResourceType: pvc
      NameSpace: demo-service
      SourceClusterName: cluster1
      TargetClusterName: cluster2
    VolumePath: /root/migrationtest

