apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: migration
  template:
    metadata:
      labels:
        name: migration
    spec:
      serviceAccountName: migration
      containers:
        - name: migration
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - migration
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "migration"
