apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanum.co.kr/openmcp/migration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nanum.co.kr/openmcp/migration
  template:
    metadata:
      labels:
        name: nanum.co.kr/openmcp/migration
    spec:
      serviceAccountName: nanum.co.kr/openmcp/migration
      containers:
        - name: nanum.co.kr/openmcp/migration
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - nanum.co.kr/openmcp/migration
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nanum.co.kr/openmcp/migration"
      imagePullSecrets:
        - name: nanumsecret
