kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: migration
subjects:
- kind: ServiceAccount
  name: migration
roleRef:
  kind: Role
  name: migration
  apiGroup: rbac.authorization.k8s.io
