kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nanum.co.kr/openmcp/migration
subjects:
- kind: ServiceAccount
  name: nanum.co.kr/openmcp/migration
roleRef:
  kind: Role
  name: nanum.co.kr/openmcp/migration
  apiGroup: rbac.authorization.k8s.io
