// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPMigration) DeepCopyInto(out *OpenMCPMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPMigration.
func (in *OpenMCPMigration) DeepCopy() *OpenMCPMigration {
	if in == nil {
		return nil
	}
	out := new(OpenMCPMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPMigrationList) DeepCopyInto(out *OpenMCPMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPMigrationList.
func (in *OpenMCPMigrationList) DeepCopy() *OpenMCPMigrationList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPMigrationSpec) DeepCopyInto(out *OpenMCPMigrationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPMigrationSpec.
func (in *OpenMCPMigrationSpec) DeepCopy() *OpenMCPMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPMigrationStatus) DeepCopyInto(out *OpenMCPMigrationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPMigrationStatus.
func (in *OpenMCPMigrationStatus) DeepCopy() *OpenMCPMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPMigrationStatus)
	in.DeepCopyInto(out)
	return out
}
